Server=my_server_ip
Login=my_user
Password=my_pass
Database=my_database
OutputDirectory=outputdir
;ReferenceTables=reftable1,reftable2
;ReplaceExistingFiles=true
;MaxParallel=1
;SingleThread=true
;SkipErrors=false
;ExtendedProperties=false
;WithDependencies=false
